title:  Apprentice Service Technical and Security Principles

permalink: pretty

defaults:
  -
    scope:
      path: "standards"
    values:
      standard: true
  -
    scope:
      path: "guides"
    values:
      guide: true
  -
    scope:
      path: "principles"
    values:
      principle: true

theme: jekyll-theme-slate
